package cmd

import (
	"fmt"
	"log"
	"os"

	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   projectName,
	Short: fmt.Sprintf("%v command line tool", projectName),
	Long:  fmt.Sprintf("%v command line tool, generated by trinity-micro ", projectName),
	Run: func(cmd *cobra.Command, args []string) {
		log.Printf("%v version: %v", projectName, version)
	},
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		log.Fatalf("root cmd execute failed, error:%v", err)
		os.Exit(1)
	}
}
